### ISSUE TITLE
Can swagger yaml be generated from vert.x routers now ? What is the approach if it's possible ? 

### ISSUE THREAD

**Issue by debashisdeb** [slinkydeveloper/vertx-web#1]
Can swagger yaml be generated from vert.x routers now ? What is the approach if it's possible ?

**Comment by slinkydeveloper** [comment]
Actually this is not a part of my GSoC 2017 project. But i'm going to talk with my mentor about it. I will update you ASAP

**Comment by pmlopes** [comment]
From the basic router one can collect the required information to identify all the routes and possibly the path paramters as well as accepted/produces content types. It is not easy to enrich this data with type information for the parameters for example. In order to do this one would need to add extra methods to the router to collect the required metadata.

Should be feasable but it is not there out of the box.

**Comment by slinkydeveloper** [comment]
@debashisdeb as @pmlopes says, the real downside is that you have to add a lot of informations manually that can't be deduced by `Route` or `ValidationHandler` object (the most important example is the responses). So, after a discussion with my mentor, i'm not going to implement it.

If you want to implement it, i'll give you a tip: To get request parameters from HttpRequestValidationImpl, just subclass all its methods and then call the super function. For example:

```java
@Override
  public HTTPRequestValidationHandler addPathParam(String parameterName, ParameterType type) {
    // some code generation function calls
    return super.addPathParam(parameterName, type);
  }
```
