### ISSUE TITLE
Question : swagger-parser vs KaiZen OpenApi Parser

### ISSUE THREAD

**Issue by phiz71** [slinkydeveloper/vertx-web#3]
Hi,

it's more a question than a real issue.

Swagger announced a few days ago, the support of OAS 3.0 in their core libraries (swagger-core & swagger-parser) : https://swagger.io/oas-3-0-support-in-swagger-core-java-libraries

Have you considered using these new libraries instead of Reprezen ones ?

**Comment by phiz71** [comment]
BTW : I've forked your repository to test the new version of Swagger-Parser. All compile, but I'm still working on making unit-tests green again :).

**Comment by slinkydeveloper** [comment]
We used KaiZen-OpenApi-Parser because when we started it was the only one! We are waiting for a response from RepreZen of various pr needed for us (you can give a look at my parser fork). We are considering as a second option to switch to a "manual" spec handling: we use a standard json parser with external derefs (seems like jackson already can do that) and we use a schema validator across oas 3 schema. This seems the faster alternative. In this situation using a parser like swagger-parser can decrease the performance and create only more problems

Also we need a function to get the json schema (for example for request bodies) that resolve refs and resolve circular dependencies. This is a thing that is hard to achieve with a parser. I tried to implement it in kaizen but they have a bug that when you load a spec with circular references it simply goes stack overflow (give a look at this issue that explains everything and has a stub of this function https://github.com/RepreZen/KaiZen-OpenApi-Parser/issues/64 ) 

My mentor @pmlopes says to wait a bit for a reprezen response, or if they don't want to answer us we want to switch to a "manual way" 

Of course if you resolve this things your help is accepted! Please keep me updated of your progress! I want as you all my work released!

**Comment by phiz71** [comment]
> We used KaiZen-OpenApi-Parser because when we started it was the only one! 

That's a very good reason ! :smile: 

> In this situation using a parser like swagger-parser can decrease the performance and create only more problems

Good point. The new version of Swagger-parser has been written from scratch, maybe performance has been improved. But maybe, new problems will happened. (I hope not too much)

> Please keep me updated of your progress!

Of course !

**Comment by phiz71** [comment]
Hi !

I've finally managed to turn all the tests green ✔️ .
I've used the last version of the swagger-parser but I had to had some corrections to it (You can check my PR here : https://github.com/swagger-api/swagger-parser/pulls?utf8=%E2%9C%93&q=author%3Aphiz71%20)

I've also fixed some part of your code (a very very small part 😉 )
Fix YAML format - https://github.com/phiz71/vertx-web/commit/911fd0cb7753046d8ff5f74ff8f94fe032935ae0 and https://github.com/phiz71/vertx-web/commit/65c42ae23ee736a451047b8036eba0b01bad30ac
Changing a test case - https://github.com/phiz71/vertx-web/commit/0512265d97ed09bf733702c5cffcc82bc4ef527b
Adding an `isOptional` in MultipartCustomValidator - https://github.com/phiz71/vertx-web/commit/b92611b5d9a0ea647221a58be2d635fb22c2a0c0

And here, you can find the comparison between your deisgndriven branch and mine
https://github.com/slinkydeveloper/vertx-web/compare/designdriven...phiz71:designdriven-with-swagger-tooling
